<a href="https://colab.research.google.com/github/Jashanpreet645/UCS712-Cognitive-Computing-Lab-/blob/main/assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRACTICE

In [ ]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(arr_2d))
print(arr_2d.dtype)
print(arr_2d.size)
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)

<class 'numpy.ndarray'>
int64
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
a = np.array([1,2,3,4,5])
a[3:5]=300
print(a)

[  1   2   3 300 300]


#Question-1

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
for i in range(len(arr)):
  arr[i] = arr[i]+2
print(f"add every elment by 2 {arr}")

arr = np.array([1,2,3,4,5])
for i in range(len(arr)):
  arr[i] = arr[i]*3
print(f"multiple every elment by 3 {arr}")

arr = np.array([1,2,3,4,5])
for i in range(len(arr)):
  arr[i] = arr[i]/2
print(f"divide every elment by 2 {arr}")

add every elment by 2 [3 4 5 6 7]
multiple every elment by 3 [ 3  6  9 12 15]
divide every elment by 2 [0 1 1 2 2]


#Question-2(a)

In [8]:
arr = np.array([1,2,3,4,5])
# reversed = np.sort(arr)[::-1]
reversed = np.flip(arr)                #for any dimension
print(reversed)

[5 4 3 2 1]


#Question-2(b)

In [10]:
import numpy as np
# y = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
x_mode = np.unique(x)
total = []
count = 0
for j in x_mode:
    count = 0
    for i in x:
        if i == j:
            count += 1
    total.append(count)
mode = x_mode[total.index(max(total))]
# print(total)
print(f"mode of the array is = {mode}")
# print(x_mode)

mode of the array is = 1


#Question-3

In [6]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"Access 1st row, 2nd column = {arr[0][1]}")
print(f"Access 3rd row, 1st column = {arr[2][0]}")

Access 1st row, 2nd column = 20
Access 3rd row, 1st column = 70


#Question-4

In [16]:
import numpy as np
arr = np.linspace(10,100,25)
print(f"the array is = {arr}")
print(f"the dim of array is = {arr.ndim}")
print(f"the shape of array is = {arr.shape}")
print(f"the total elm in array is = {arr.size}")
print(f"the data type of array is = {arr.dtype}")
print(f"the bytes in array is = {arr.nbytes}")
reshaped_array = arr.reshape(25,1)
print(f"the transpose of array is = \n{reshaped_array}")
# print(f"the transpose of array is = {arr.transpose}")

transpose_array = arr.reshape(25,1).T
print(f"the array is = {transpose_array}")

# Note: The original 1-D array cannot be transposed directly using T attribute.
# It needs to be reshaped to a 2-D array first.

the array is = [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
the dim of array is = 1
the shape of array is = (25,)
the total elm in array is = 25
the data type of array is = float64
the bytes in array is = 200
the transpose of array is = 
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
the array is = [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


#Question-5

In [27]:
import numpy as np
ucs420_arr = np.array([[10, 20, 30, 40],
                              [50, 60, 70, 80],
                              [90, 15, 20, 35]])

print("Original Array :\n", ucs420_arr)

mean_value = np.mean(ucs420_arr)
print(f"mean of the array = {mean_value}")

median_value = np.median(ucs420_arr)
print(f"median of the array = {median_value}")

max_value = np.max(ucs420_arr)
print(f"max of the array = {max_value}")

min_value = np.min(ucs420_arr)
print(f"min of the array = {min_value}")

unique_value = np.unique(ucs420_arr)
print(f"unique of the array = {unique_value}")

reshape_ucs420_arr = ucs420_arr.reshape(4,3)
print(f"reshaped array =\n {reshape_ucs420_arr}")

resized_ucs420_arr = np.resize(ucs420_arr,(2,3))
print(f"mean of the array =\n {resized_ucs420_arr}")

Original Array :
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean of the array = 43.333333333333336
median of the array = 37.5
max of the array = 90
min of the array = 10
unique of the array = [10 15 20 30 35 40 50 60 70 80 90]
reshaped array =
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
mean of the array =
 [[10 20 30]
 [40 50 60]]
